version: '3.9'

services:
  api:  #image nome
    build: ./app
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
  
  frontend:
    build: ./frontend
    ports:
      - 5173:5173
    volumes:
      - ./frontend:/frontend

      
